// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irghmdrfftqbecpkutit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ2htZHJmZnRxYmVjcGt1dGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDMxNjgsImV4cCI6MjA1Mjk3OTE2OH0.hrwgjEO3qkss1j4lvLX8VcbPG9pmNq0O9xT8cNJntWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);