
name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cafeteria-app-build
        path: dist/
        retention-days: 30
        
    - name: Create portable package
      run: |
        mkdir -p portable-app
        cp -r dist/* portable-app/
        echo "@echo off" > portable-app/run.bat
        echo "cd /d \"%~dp0\"" >> portable-app/run.bat
        echo "echo Demarrage du serveur local..." >> portable-app/run.bat
        echo "echo Ouvrez votre navigateur et allez a: http://localhost:8080" >> portable-app/run.bat
        echo "echo Appuyez sur Ctrl+C pour arreter le serveur" >> portable-app/run.bat
        echo "echo." >> portable-app/run.bat
        echo "start http://localhost:8080" >> portable-app/run.bat
        echo "npx serve . -p 8080 || python -m http.server 8080 --bind 127.0.0.1" >> portable-app/run.bat
        echo "pause" >> portable-app/run.bat
        echo "# Application Cafétéria Portable" > portable-app/README.txt
        echo "" >> portable-app/README.txt
        echo "Pour utiliser cette application :" >> portable-app/README.txt
        echo "1. Double-cliquez sur run.bat (Windows)" >> portable-app/README.txt
        echo "2. Si le navigateur ne s'ouvre pas automatiquement," >> portable-app/README.txt
        echo "   ouvrez manuellement: http://localhost:8080" >> portable-app/README.txt
        echo "3. Pour arrêter: fermez la fenêtre de commande" >> portable-app/README.txt
        echo "" >> portable-app/README.txt
        echo "REQUIS: Node.js doit être installé pour un fonctionnement optimal" >> portable-app/README.txt
        echo "Sinon, utilisez GitHub Pages ou Live Server" >> portable-app/README.txt
        echo "L'application fonctionne entièrement hors ligne !" >> portable-app/README.txt
        
    - name: Upload portable package
      uses: actions/upload-artifact@v4
      with:
        name: cafeteria-app-portable
        path: portable-app/
        retention-days: 30

  build-desktop-windows:
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Electron dependencies
      run: npm install electron electron-builder --save-dev
      
    - name: Build web application first
      run: npm run build
      
    - name: Build Windows Electron app
      run: npm run electron-pack-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: cafeteria-app-desktop-windows
        path: dist/*.exe
        retention-days: 30

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
